### PR TITLE
multiple fixes in setup / walkthrough

### PR DESCRIPTION
**Pull request by ux51ekac**
since I had some issues using it as it was before I thought I'd invest some hours...

* update wizard version (package name changed)
* validate inputs, give error messages and hints [2]
* use file picker also for mathhub dir
* bugfix: validate jar paths entered manually without file picker 

TODO (discuss)
* should the MathHub path really be fix after set once?
* is it really necessary to check if the jar is called `MMT.jar`? how about eg. versioned file names?
* can / should we check a signature of `MMT.jar` before running it?
* currently I give a warning [3] if the mmt version could not be detected
  - should this rather be an error?
  - in my case it is because `java` is not in `$PATH`, wasn't there some while ago an option to select the java path?
* please have a look at the hint-texts

Initial view looks now like this

image

[2] Validation errors look like this

image

------
[3]
image

### CODE REVIEW

**Comment by Jazzpirate** [comment]
that looks very nice :) I'll take a closer look soonish (possibly only when we're back from cicm), but looking at the code this very much looks like the right thing to do :)

**Comment by Jazzpirate** [comment]
> TODO (discuss)
> 
> * should the MathHub path really be fix after set once?

I would guess that there's no good way to avoid that, since `pdflatex` needs to know the *same* directory and has its own logic to find it...

> * is it really necessary to check if the jar is called `MMT.jar`? how about eg. versioned file names?

That would be possible, yes, although there's (so far) no good use case to use separate versions of MMT - that might change in the future though, so I also have no real reason to *insist* on it being called `mmt.jar`

> * can / should we check a signature of `MMT.jar` before running it?

That's basically what I use the version check for, which has the advantage that it *additionally* checks whether java works. But again: No reason to insist that we don't :)

> * currently I give a warning [3] if the mmt version could not be detected
>   * should this rather be an error?
>   * in my case it is because `java` is not in `$PATH`, wasn't there some while ago an option to select the java path?

The version could be wrongly detected simply because a user picked the wrong file. Throwing an error there seems harsh. But the setup shouldn't be allowed to continue if the version can't be detected, since that points to something being horrendously wrong.

There previously existed a logic that tries to determine the *full* path to a user's java executable, but that wreaked havoc on Michael's machine, because it detected the *wrong* java. IntelliJ-users have several of those lying around. I therefore (for now) opted for the workflow that requires a user having a `java` in their `$PATH`. That seems very reasonable to me (since that's the default if you just... well, install java), but I'm open to alternatives.

> * please have a look at the hint-texts

I notice that it's somewhat weird to have a error message `Path does not exist` for the mathhub-option, while also saying `Can be a new (empty) directory`, which kind-of suggests that the directory will be newly created if it doesn't exist... should we just create it if it doesn't exist maybe?

**Comment by ux51ekac** [comment]
thanks for the fast reply :astonished: 

> I would guess that there's no good way to avoid that, since `pdflatex` needs to know the _same_ directory and has its own logic to find it...

nonetheless might be possible to move the folder or whatever, the user has to reinstall the extension then, without knowing why. I think there should be at least an option to recheck the env variable or sth like that.

> That's basically what I use the version check for, which has the advantage that it _additionally_ checks whether java works. But again: No reason to insist that we don't :)

with signature checking is more of a "this mmt is officially downloaded from mathhub"-thing that would be somewhat more elaborate to do...
 
> The version could be wrongly detected simply because a user picked the wrong file. Throwing an error there seems harsh. But the setup shouldn't be allowed to continue if the version can't be detected, since that points to something being horrendously wrong.

how about using the value from `$PATH` as default making it possible to change in the settings?

> I notice that it's somewhat weird to have a error message `Path does not exist` for the mathhub-option, while also saying `Can be a new (empty) directory`, which kind-of suggests that the directory will be newly created if it doesn't exist... should we just create it if it doesn't exist maybe?

that sounds like a good idea

**Comment by ux51ekac** [comment]
> If I'm mistaken: what _should_ happen is that the IDE always(!) determines the mathhub directory by 1. checking the system variable or 2. checking $HOME/.stex. If neither yields a valid directory, the setup should show up.

you are right, the env var will also be checked each time the extension starts. i forgot that.
we should probably be more transparent with that `$HOME/.stex/` folder, or think again about a corss-platform way to persist the mathhub environment variable in a standardized way (`~/.profile` on *nix, `System.Environment` on windows, sth like that).

> That definitely shouldn't happen, since I couldn't use the IDE anymore then :D I build it locally on the devel-branch, after all ;)

i mean i understand your concerns, nevertheless signing could happen on build automatically ([jarsigner](https://docs.oracle.com/javase/tutorial/deployment/jar/verify.html) is the keyword to search for if you are interested).
imo this will be a thing to discuss eventually since the jar will end up on client computers.

**Comment by ux51ekac** [comment]
ready for review.

i will do a code cleanup follow-up branch after this is merged. this file and others will be refactored and split up.

**Comment by Jazzpirate** [comment]
Looks good to me - thank you :)

**Pull request merged**
